style = "blue"
indent = 3
margin = 84
always_for_in = true
for_in_replacement = "in"
whitespace_typedefs = true
whitespace_ops_in_indices = false
remove_extra_newlines = true
import_to_using = false
pipe_to_function_call = false
short_to_long_function_def = false
long_to_short_function_def = false
always_use_return = false
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = false
format_docstrings = true
align_struct_field = false
align_conditional = false
align_assignment = false
align_pair_arrow = false
conditional_to_if = false
normalize_line_endings = "auto"
align_matrix = true
trailing_comma = true
trailing_zero = true
indent_submodule = false
separate_kwargs_with_semicolon = true
surround_whereop_typeparameters = true
format_markdown = true
