[config]
factor = "energy_transfer"
values = "exp10.(range(start=log10(0.01), stop=log10(0.3), length=24))"
num_steps = 2880
num_replications = 100
output = "outputs/energy-transfer"

[config.params]
map_size = 125
flower_width = 0
init_pr_eliminate = 0.0
init_num_bphs = 200
