[[config]]
factor = "energy_transfer"
values = "range(start=0.3, stop=0.03, length=9)"
num_steps = 5660
num_replications = 100
output = "outputs/energy-transfer-1"
    [config.params]
    map_size = 250
    flower_width = 0
    init_pr_eliminate = 0.0
    num_init_bphs = 200

[[config]]
factor = "energy_transfer"
values = "range(start=0.1, stop=0.01, length=9)"
num_steps = 5660
num_replications = 100
output = "outputs/energy-transfer-2"
    [config.params]
    map_size = 250
    flower_width = 0
    init_pr_eliminate = 0.0
    num_init_bphs = 200

[[config]]
factor = "energy_transfer"
values = "range(start=0.06, stop=0.01, length=9)"
num_steps = 5660
num_replications = 100
output = "outputs/energy-transfer-3"
    [config.params]
    map_size = 250
    flower_width = 0
    init_pr_eliminate = 0.0
    num_init_bphs = 200
