[[config]]
data = "outputs/init-pr-eliminate-1"
column = "num_bphs"
output = "docs/src/assets/fig-3a1.png"
normalize_y = false
stable_steps = false

[[config]]
data = "outputs/init-pr-eliminate-1"
column = "pct_rices"
output = "docs/src/assets/fig-3b1.png"
normalize_y = true
stable_steps = false

[[config]]
data = "outputs/init-pr-eliminate-1"
column = "pct_nymphs"
output = "docs/src/assets/fig-3c1.png"
normalize_y = true
stable_steps = false

[[config]]
data = "outputs/init-pr-eliminate-2"
column = "num_bphs"
output = "docs/src/assets/fig-3a2.png"
normalize_y = false
stable_steps = false

[[config]]
data = "outputs/init-pr-eliminate-2"
column = "pct_rices"
output = "docs/src/assets/fig-3b2.png"
normalize_y = true
stable_steps = false

[[config]]
data = "outputs/init-pr-eliminate-2"
column = "pct_nymphs"
output = "docs/src/assets/fig-3c2.png"
normalize_y = true
stable_steps = false

[[config]]
data = "outputs/init-pr-eliminate-3"
column = "num_bphs"
output = "docs/src/assets/fig-3a3.png"
normalize_y = false
stable_steps = false

[[config]]
data = "outputs/init-pr-eliminate-3"
column = "pct_rices"
output = "docs/src/assets/fig-3b3.png"
normalize_y = true
stable_steps = false

[[config]]
data = "outputs/init-pr-eliminate-3"
column = "pct_nymphs"
output = "docs/src/assets/fig-3c3.png"
normalize_y = true
stable_steps = false
