[[config]]
data = "outputs/energy-transfer-02"
column = "num_bphs"
output = "docs/src/assets/fig-1a.png"
normalize_y = false
stable_steps = false

[[config]]
data = "outputs/energy-transfer-03"
column = "num_bphs"
output = "docs/src/assets/fig-1b.png"
normalize_y = false
stable_steps = false
