[config]
factor = "flower_width"
values = "1:20"
num_steps = 2880
num_replications = 100
output = "outputs/flower-width"

[config.params]
map_size = 125
init_pr_eliminate = 0.1
init_num_bphs = 200
energy_transfer = 0.025
