[[config]]
factor = "flower_width"
values = "1:2:17"
num_steps = 2880
num_replications = 100
output = "outputs/flower-width-1"
    [config.params]
    map_size = 125
    init_pr_eliminate = 0.06
    num_init_bphs = 200
    energy_transfer = 0.032
    
[[config]]
factor = "flower_width"
values = "1:2:17"
num_steps = 2880
num_replications = 100
output = "outputs/flower-width-2"
    [config.params]
    map_size = 125
    init_pr_eliminate = 0.09
    num_init_bphs = 200
    energy_transfer = 0.032

[[config]]
factor = "flower_width"
values = "1:2:17"
num_steps = 2880
num_replications = 100
output = "outputs/flower-width-3"
    [config.params]
    map_size = 125
    init_pr_eliminate = 0.12
    num_init_bphs = 200
    energy_transfer = 0.032

[[config]]
factor = "flower_width"
values = "1:2:17"
num_steps = 2880
num_replications = 100
output = "outputs/flower-width-4"
    [config.params]
    map_size = 125
    init_pr_eliminate = 0.15
    num_init_bphs = 200
    energy_transfer = 0.032
