[config]
factor = "init_pr_eliminate"
values = "exp10.(range(start=log10(0.01), stop=log10(0.2), length=24))"
num_steps = 2880
num_replications = 100
output = "outputs/init-pr-eliminate"

[config.params]
map_size = 125
flower_width = 7
init_num_bphs = 200
energy_transfer = 0.035
