[config]
factor = "num_init_bphs"
values = "trunc.(Int, range(start=20, stop=600, length=9))"
num_steps = 2880
num_replications = 100
output = "outputs/num-init-bphs"

[config.params]
map_size = 125
flower_width = 0
init_pr_eliminate = 0.0
energy_transfer = 0.032
