[config]
num_steps = 2880
spu = 1
framerate =  60
seed = 1
video_output = "outputs/video.mp4"

[config.params]
flower_width = 0
map_size = 125
init_pr_eliminate = 0.0
init_num_bphs = 200
energy_transfer = 0.032
